version: "3"

services:
  api:
    env_file: .env
    container_name: "microservice-api"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE: production
        PORT: ${PORT}
    environment:
      - 'PORT=${PORT}'
    ports:
      - "${PORT}:${PORT}"
    restart: 'always'
    command: npm run start